language: python

python:
- "3.2"
- "3.3"
- "3.4"
- "3.5.0b3"
- "nightly"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      # Package list from http://bazel.io/docs/install.html
      - openjdk-7-jdk
      - openjdk-7-source
      - pkg-config
      - zip
      - zlib1g-dev

# Eventually, Bazel will have binary packages and we'll be able to
# just download a prebuilt distribution of Bazel. For now, build it
# from source every time.
before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.0/bazel-0.1.0-installer-linux-x86_64.sh'
  - sha256sum -c tools/bazel-0.1.0-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-0.1.0-installer-linux-x86_64.sh
  - ./bazel-0.1.0-installer-linux-x86_64.sh --user
  - cat ~/.bazelrc >> ./tools/bazelrc

script:
  - bazel --bazelrc=tools/bazelrc test --test_output=all //:tabletest3_test

sudo: false
